name: dart_epoxy
author: "Keaton Brandt <keaton.brandt@gmail.com>"
description: "The reactive glue for Dart"
homepage: "https://github.com/KeatonTech/epoxy"
version: "0.1.0"
dev_dependencies:
    test:
    matcher:
dependencies:
    meta: ">=1.1.2 <2.0.0"
